public class Globals {
    /*
    public static IP_ADDRESS_RESPONSE =
    {
        "status":"success",
            "country":"United States",
            "countryCode":"US",
            "region":"CA",
            "regionName":"California",
            "city":"Pasadena",
            "zip":"91107",
            "lat":34.1563,
            "lon":-118.0868,
            "timezone":"America/Los_Angeles",
            "isp":"Spectrum",
            "org":"Charter Communications",
            "as":"AS20115 Charter Communications",
            "query":"47.41.30.196"
    };

    public static ADDRESS_ADDRESS_RESPONSE =
    {
        "results" : [
        {
            "address_components" : [
            {
                "long_name" : "444",
                    "short_name" : "444",
                    "types" : [ "street_number" ]
            },
            {
                "long_name" : "North Euclid Avenue",
                    "short_name" : "N Euclid Ave",
                    "types" : [ "route" ]
            },
            {
                "long_name" : "Pasadena",
                    "short_name" : "Pasadena",
                    "types" : [ "locality", "political" ]
            },
            {
                "long_name" : "Los Angeles County",
                    "short_name" : "Los Angeles County",
                    "types" : [ "administrative_area_level_2", "political" ]
            },
            {
                "long_name" : "California",
                    "short_name" : "CA",
                    "types" : [ "administrative_area_level_1", "political" ]
            },
            {
                "long_name" : "United States",
                    "short_name" : "US",
                    "types" : [ "country", "political" ]
            },
            {
                "long_name" : "91101",
                    "short_name" : "91101",
                    "types" : [ "postal_code" ]
            }
              ],
            "formatted_address" : "444 N Euclid Ave, Pasadena, CA 91101, USA",
                "geometry" : {
            "location" : {
                "lat" : 34.153571,
                        "lng" : -118.1426581
            },
            "location_type" : "ROOFTOP",
                    "viewport" : {
                "northeast" : {
                    "lat" : 34.1549199802915,
                            "lng" : -118.1413091197085
                },
                "southwest" : {
                    "lat" : 34.1522220197085,
                            "lng" : -118.1440070802915
                }
            }
        },
            "place_id" : "ChIJ_Sk3vGzDwoARDSZPtofrD5I",
                "plus_code" : {
            "compound_code" : "5V34+CW Pasadena, California, United States",
                    "global_code" : "85635V34+CW"
        },
            "types" : [ "street_address" ]
        }
        ],
        "status" : "OK"
    }

    public static FORECAST_RESPONSE =
    {
        "latitude": 34.153571,
            "longitude": -118.1426581,
            "timezone": "America/Los_Angeles",
            "currently": {
        "time": 1573141888,
                "summary": "Overcast",
                "icon": "cloudy",
                "nearestStormDistance": 15,
                "nearestStormBearing": 45,
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 64.6,
                "apparentTemperature": 64.6,
                "dewPoint": 38.25,
                "humidity": 0.38,
                "pressure": 1018.6,
                "windSpeed": 1.78,
                "windGust": 3.51,
                "windBearing": 33,
                "cloudCover": 0.95,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 282.4
    },
        "hourly": {
        "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "data": [
        {
            "time": 1573138800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 59.75,
                "apparentTemperature": 59.75,
                "dewPoint": 38.06,
                "humidity": 0.44,
                "pressure": 1018.2,
                "windSpeed": 2.34,
                "windGust": 4.06,
                "windBearing": 32,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 282.1
        },
        {
            "time": 1573142400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.42,
                "apparentTemperature": 65.42,
                "dewPoint": 38.3,
                "humidity": 0.37,
                "pressure": 1018.7,
                "windSpeed": 1.71,
                "windGust": 3.47,
                "windBearing": 37,
                "cloudCover": 0.94,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 282.4
        },
        {
            "time": 1573146000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 70.55,
                "apparentTemperature": 70.55,
                "dewPoint": 38.69,
                "humidity": 0.31,
                "pressure": 1019,
                "windSpeed": 1.58,
                "windGust": 3.79,
                "windBearing": 196,
                "cloudCover": 0.74,
                "uvIndex": 2,
                "visibility": 9.637,
                "ozone": 282.6
        },
        {
            "time": 1573149600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 74.12,
                "apparentTemperature": 74.12,
                "dewPoint": 37.98,
                "humidity": 0.27,
                "pressure": 1019.2,
                "windSpeed": 2.48,
                "windGust": 3.79,
                "windBearing": 209,
                "cloudCover": 0.31,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 282.8
        },
        {
            "time": 1573153200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 77.64,
                "apparentTemperature": 77.64,
                "dewPoint": 36.91,
                "humidity": 0.23,
                "pressure": 1018.8,
                "windSpeed": 4,
                "windGust": 5.62,
                "windBearing": 193,
                "cloudCover": 0.03,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 282.7
        },
        {
            "time": 1573156800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.001,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 80.36,
                "apparentTemperature": 80.36,
                "dewPoint": 37.05,
                "humidity": 0.21,
                "pressure": 1018.2,
                "windSpeed": 4.82,
                "windGust": 6.54,
                "windBearing": 207,
                "cloudCover": 0.02,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 282.6
        },
        {
            "time": 1573160400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 81.83,
                "apparentTemperature": 81.83,
                "dewPoint": 37.34,
                "humidity": 0.2,
                "pressure": 1017.3,
                "windSpeed": 5.34,
                "windGust": 7.18,
                "windBearing": 222,
                "cloudCover": 0.01,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 282.5
        },
        {
            "time": 1573164000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 81.88,
                "apparentTemperature": 81.88,
                "dewPoint": 39.07,
                "humidity": 0.22,
                "pressure": 1017.5,
                "windSpeed": 5.24,
                "windGust": 7.08,
                "windBearing": 231,
                "cloudCover": 0.01,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 282.2
        },
        {
            "time": 1573167600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 80.75,
                "apparentTemperature": 80.75,
                "dewPoint": 41.74,
                "humidity": 0.25,
                "pressure": 1017.5,
                "windSpeed": 4.75,
                "windGust": 6.51,
                "windBearing": 241,
                "cloudCover": 0.01,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 282
        },
        {
            "time": 1573171200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 78.23,
                "apparentTemperature": 78.23,
                "dewPoint": 42.75,
                "humidity": 0.28,
                "pressure": 1017.4,
                "windSpeed": 3.8,
                "windGust": 5.95,
                "windBearing": 238,
                "cloudCover": 0.01,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 282
        },
        {
            "time": 1573174800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 73.52,
                "apparentTemperature": 73.52,
                "dewPoint": 43.18,
                "humidity": 0.34,
                "pressure": 1018.1,
                "windSpeed": 3.6,
                "windGust": 5.26,
                "windBearing": 181,
                "cloudCover": 0.01,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 282.2
        },
        {
            "time": 1573178400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0.0007,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 69.93,
                "apparentTemperature": 69.93,
                "dewPoint": 42.17,
                "humidity": 0.37,
                "pressure": 1018.4,
                "windSpeed": 3.59,
                "windGust": 5.16,
                "windBearing": 74,
                "cloudCover": 0.01,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 282.7
        },
        {
            "time": 1573182000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 67.74,
                "apparentTemperature": 67.74,
                "dewPoint": 39.58,
                "humidity": 0.36,
                "pressure": 1018.2,
                "windSpeed": 3.72,
                "windGust": 4.82,
                "windBearing": 23,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 283.1
        },
        {
            "time": 1573185600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.59,
                "apparentTemperature": 66.59,
                "dewPoint": 38.3,
                "humidity": 0.35,
                "pressure": 1019.2,
                "windSpeed": 3.69,
                "windGust": 4.45,
                "windBearing": 43,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 283
        },
        {
            "time": 1573189200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.03,
                "apparentTemperature": 66.03,
                "dewPoint": 36.46,
                "humidity": 0.33,
                "pressure": 1019.8,
                "windSpeed": 4.14,
                "windGust": 4.49,
                "windBearing": 63,
                "cloudCover": 0.04,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 282.8
        },
        {
            "time": 1573192800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.44,
                "apparentTemperature": 66.44,
                "dewPoint": 33.25,
                "humidity": 0.29,
                "pressure": 1019.8,
                "windSpeed": 3.75,
                "windGust": 3.75,
                "windBearing": 50,
                "cloudCover": 0.06,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 282.7
        },
        {
            "time": 1573196400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.81,
                "apparentTemperature": 65.81,
                "dewPoint": 31.4,
                "humidity": 0.28,
                "pressure": 1019.7,
                "windSpeed": 3.87,
                "windGust": 3.87,
                "windBearing": 41,
                "cloudCover": 0.07,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 282.8
        },
        {
            "time": 1573200000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.28,
                "apparentTemperature": 65.28,
                "dewPoint": 29.57,
                "humidity": 0.26,
                "pressure": 1019.8,
                "windSpeed": 4.21,
                "windGust": 4.21,
                "windBearing": 34,
                "cloudCover": 0.09,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 283
        },
        {
            "time": 1573203600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.04,
                "apparentTemperature": 65.04,
                "dewPoint": 27.58,
                "humidity": 0.24,
                "pressure": 1019.6,
                "windSpeed": 4.42,
                "windGust": 4.43,
                "windBearing": 31,
                "cloudCover": 0.14,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 283.1
        },
        {
            "time": 1573207200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 64.6,
                "apparentTemperature": 64.6,
                "dewPoint": 25.52,
                "humidity": 0.23,
                "pressure": 1019.5,
                "windSpeed": 4.64,
                "windGust": 4.64,
                "windBearing": 33,
                "cloudCover": 0.12,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 283.2
        },
        {
            "time": 1573210800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 64.16,
                "apparentTemperature": 64.16,
                "dewPoint": 23.63,
                "humidity": 0.21,
                "pressure": 1019.4,
                "windSpeed": 4.98,
                "windGust": 4.98,
                "windBearing": 34,
                "cloudCover": 0.11,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 283.2
        },
        {
            "time": 1573214400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 64.2,
                "apparentTemperature": 64.2,
                "dewPoint": 21.9,
                "humidity": 0.2,
                "pressure": 1019.7,
                "windSpeed": 5.19,
                "windGust": 5.19,
                "windBearing": 33,
                "cloudCover": 0.08,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 283.1
        },
        {
            "time": 1573218000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 64.09,
                "apparentTemperature": 64.09,
                "dewPoint": 20.4,
                "humidity": 0.19,
                "pressure": 1019.8,
                "windSpeed": 5.5,
                "windGust": 5.5,
                "windBearing": 30,
                "cloudCover": 0.04,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 282.7
        },
        {
            "time": 1573221600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 63.64,
                "apparentTemperature": 63.64,
                "dewPoint": 19.16,
                "humidity": 0.18,
                "pressure": 1019.6,
                "windSpeed": 5.79,
                "windGust": 5.79,
                "windBearing": 27,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 282.1
        },
        {
            "time": 1573225200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 64.12,
                "apparentTemperature": 64.12,
                "dewPoint": 18.93,
                "humidity": 0.17,
                "pressure": 1020,
                "windSpeed": 5.72,
                "windGust": 5.72,
                "windBearing": 30,
                "cloudCover": 0.01,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 281.7
        },
        {
            "time": 1573228800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 68.64,
                "apparentTemperature": 68.64,
                "dewPoint": 18.63,
                "humidity": 0.15,
                "pressure": 1020.3,
                "windSpeed": 4.58,
                "windGust": 4.82,
                "windBearing": 38,
                "cloudCover": 0,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 281.5
        },
        {
            "time": 1573232400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 74.39,
                "apparentTemperature": 74.39,
                "dewPoint": 18.34,
                "humidity": 0.12,
                "pressure": 1021,
                "windSpeed": 3.45,
                "windGust": 4.04,
                "windBearing": 61,
                "cloudCover": 0,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 281.4
        },
        {
            "time": 1573236000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 79.34,
                "apparentTemperature": 79.34,
                "dewPoint": 17.77,
                "humidity": 0.1,
                "pressure": 1021.2,
                "windSpeed": 2.87,
                "windGust": 3.66,
                "windBearing": 70,
                "cloudCover": 0,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 281.3
        },
        {
            "time": 1573239600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 82.98,
                "apparentTemperature": 82.98,
                "dewPoint": 16.75,
                "humidity": 0.08,
                "pressure": 1020.4,
                "windSpeed": 2.91,
                "windGust": 3.91,
                "windBearing": 86,
                "cloudCover": 0,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 281.4
        },
        {
            "time": 1573243200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 85.56,
                "apparentTemperature": 85.56,
                "dewPoint": 16.05,
                "humidity": 0.08,
                "pressure": 1019.1,
                "windSpeed": 3.29,
                "windGust": 4.53,
                "windBearing": 188,
                "cloudCover": 0,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 281.5
        },
        {
            "time": 1573246800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 87.13,
                "apparentTemperature": 87.13,
                "dewPoint": 16.22,
                "humidity": 0.07,
                "pressure": 1018.3,
                "windSpeed": 3.56,
                "windGust": 5.04,
                "windBearing": 221,
                "cloudCover": 0,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 281
        },
        {
            "time": 1573250400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 87.3,
                "apparentTemperature": 87.3,
                "dewPoint": 17.64,
                "humidity": 0.08,
                "pressure": 1017.9,
                "windSpeed": 3.65,
                "windGust": 5.44,
                "windBearing": 181,
                "cloudCover": 0,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 279.8
        },
        {
            "time": 1573254000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 86.7,
                "apparentTemperature": 86.7,
                "dewPoint": 19.74,
                "humidity": 0.08,
                "pressure": 1018.3,
                "windSpeed": 3.56,
                "windGust": 5.81,
                "windBearing": 305,
                "cloudCover": 0,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 278.1
        },
        {
            "time": 1573257600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 84.15,
                "apparentTemperature": 84.15,
                "dewPoint": 22.08,
                "humidity": 0.1,
                "pressure": 1018.3,
                "windSpeed": 3.47,
                "windGust": 5.91,
                "windBearing": 300,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 276.9
        },
        {
            "time": 1573261200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 79.54,
                "apparentTemperature": 79.54,
                "dewPoint": 24.08,
                "humidity": 0.13,
                "pressure": 1018.5,
                "windSpeed": 4.2,
                "windGust": 5.52,
                "windBearing": 353,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 276.7
        },
        {
            "time": 1573264800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 75.95,
                "apparentTemperature": 75.95,
                "dewPoint": 25.13,
                "humidity": 0.15,
                "pressure": 1018.8,
                "windSpeed": 4.89,
                "windGust": 5.25,
                "windBearing": 35,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 276.9
        },
        {
            "time": 1573268400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 73.43,
                "apparentTemperature": 73.43,
                "dewPoint": 25.41,
                "humidity": 0.17,
                "pressure": 1019.1,
                "windSpeed": 5.14,
                "windGust": 5.26,
                "windBearing": 30,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 276.8
        },
        {
            "time": 1573272000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 71.87,
                "apparentTemperature": 71.87,
                "dewPoint": 24.73,
                "humidity": 0.17,
                "pressure": 1019.3,
                "windSpeed": 5.3,
                "windGust": 5.44,
                "windBearing": 32,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 275.8
        },
        {
            "time": 1573275600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 71.1,
                "apparentTemperature": 71.1,
                "dewPoint": 23.22,
                "humidity": 0.16,
                "pressure": 1019.2,
                "windSpeed": 5.44,
                "windGust": 5.69,
                "windBearing": 35,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 274.3
        },
        {
            "time": 1573279200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 70.38,
                "apparentTemperature": 70.38,
                "dewPoint": 21.5,
                "humidity": 0.16,
                "pressure": 1019.1,
                "windSpeed": 5.49,
                "windGust": 5.83,
                "windBearing": 36,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 273
        },
        {
            "time": 1573282800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 69.41,
                "apparentTemperature": 69.41,
                "dewPoint": 19.72,
                "humidity": 0.15,
                "pressure": 1019,
                "windSpeed": 5.7,
                "windGust": 5.9,
                "windBearing": 35,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 272.2
        },
        {
            "time": 1573286400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 68.89,
                "apparentTemperature": 68.89,
                "dewPoint": 17.76,
                "humidity": 0.14,
                "pressure": 1018.6,
                "windSpeed": 5.87,
                "windGust": 5.92,
                "windBearing": 32,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 271.5
        },
        {
            "time": 1573290000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 68.29,
                "apparentTemperature": 68.29,
                "dewPoint": 16.16,
                "humidity": 0.13,
                "pressure": 1018.6,
                "windSpeed": 5.95,
                "windGust": 5.96,
                "windBearing": 29,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 270.6
        },
        {
            "time": 1573293600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 68.12,
                "apparentTemperature": 68.12,
                "dewPoint": 14.64,
                "humidity": 0.13,
                "pressure": 1018.1,
                "windSpeed": 6.08,
                "windGust": 6.08,
                "windBearing": 29,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 269.4
        },
        {
            "time": 1573297200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 67.8,
                "apparentTemperature": 67.8,
                "dewPoint": 13.41,
                "humidity": 0.12,
                "pressure": 1017.4,
                "windSpeed": 6.19,
                "windGust": 6.19,
                "windBearing": 29,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 268.2
        },
        {
            "time": 1573300800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 67.88,
                "apparentTemperature": 67.88,
                "dewPoint": 12.36,
                "humidity": 0.11,
                "pressure": 1017.2,
                "windSpeed": 6.29,
                "windGust": 6.29,
                "windBearing": 29,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 267.1
        },
        {
            "time": 1573304400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 68.78,
                "apparentTemperature": 68.78,
                "dewPoint": 11.24,
                "humidity": 0.11,
                "pressure": 1016.9,
                "windSpeed": 7.15,
                "windGust": 7.15,
                "windBearing": 29,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 266.3
        },
        {
            "time": 1573308000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 67.63,
                "apparentTemperature": 67.63,
                "dewPoint": 11.43,
                "humidity": 0.11,
                "pressure": 1017.6,
                "windSpeed": 7.42,
                "windGust": 7.42,
                "windBearing": 27,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 265.7
        },
        {
            "time": 1573311600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 67.42,
                "apparentTemperature": 67.42,
                "dewPoint": 12.23,
                "humidity": 0.12,
                "pressure": 1017.8,
                "windSpeed": 7.22,
                "windGust": 7.22,
                "windBearing": 31,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 264.8
        }
          ]
    },
        "daily": {
        "summary": "No precipitation throughout the week.",
                "icon": "clear-day",
                "data": [
        {
            "time": 1573113600,
                "summary": "Foggy in the morning.",
                "icon": "fog",
                "sunriseTime": 1573136340,
                "sunsetTime": 1573174560,
                "moonPhase": 0.36,
                "precipIntensity": 0.0002,
                "precipIntensityMax": 0.0013,
                "precipIntensityMaxTime": 1573185900,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperatureHigh": 82.51,
                "temperatureHighTime": 1573162260,
                "temperatureLow": 63.08,
                "temperatureLowTime": 1573223280,
                "apparentTemperatureHigh": 82.01,
                "apparentTemperatureHighTime": 1573162260,
                "apparentTemperatureLow": 63.57,
                "apparentTemperatureLowTime": 1573223280,
                "dewPoint": 38.76,
                "humidity": 0.35,
                "pressure": 1018,
                "windSpeed": 3.35,
                "windGust": 7.22,
                "windGustTime": 1573161480,
                "windBearing": 182,
                "cloudCover": 0.41,
                "uvIndex": 4,
                "uvIndexTime": 1573155360,
                "visibility": 7.909,
                "ozone": 282,
                "temperatureMin": 58.59,
                "temperatureMinTime": 1573120380,
                "temperatureMax": 82.51,
                "temperatureMaxTime": 1573162260,
                "apparentTemperatureMin": 59.08,
                "apparentTemperatureMinTime": 1573120380,
                "apparentTemperatureMax": 82.01,
                "apparentTemperatureMaxTime": 1573162260
        },
        {
            "time": 1573200000,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1573222800,
                "sunsetTime": 1573260900,
                "moonPhase": 0.39,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipIntensityMaxTime": 1573262400,
                "precipProbability": 0,
                "temperatureHigh": 87.86,
                "temperatureHighTime": 1573248900,
                "temperatureLow": 66.69,
                "temperatureLowTime": 1573310460,
                "apparentTemperatureHigh": 87.36,
                "apparentTemperatureHighTime": 1573248900,
                "apparentTemperatureLow": 67.18,
                "apparentTemperatureLowTime": 1573310460,
                "dewPoint": 21.16,
                "humidity": 0.15,
                "pressure": 1019.4,
                "windSpeed": 4.53,
                "windGust": 5.93,
                "windGustTime": 1573256820,
                "windBearing": 32,
                "cloudCover": 0.02,
                "uvIndex": 4,
                "uvIndexTime": 1573241820,
                "visibility": 10,
                "ozone": 279.4,
                "temperatureMin": 63.08,
                "temperatureMinTime": 1573223280,
                "temperatureMax": 87.86,
                "temperatureMaxTime": 1573248900,
                "apparentTemperatureMin": 63.57,
                "apparentTemperatureMinTime": 1573223280,
                "apparentTemperatureMax": 87.36,
                "apparentTemperatureMaxTime": 1573248900
        },
        {
            "time": 1573286400,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1573309260,
                "sunsetTime": 1573347240,
                "moonPhase": 0.43,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipIntensityMaxTime": 1573351920,
                "precipProbability": 0,
                "temperatureHigh": 87.88,
                "temperatureHighTime": 1573334520,
                "temperatureLow": 64.65,
                "temperatureLowTime": 1573396380,
                "apparentTemperatureHigh": 87.38,
                "apparentTemperatureHighTime": 1573334520,
                "apparentTemperatureLow": 65.14,
                "apparentTemperatureLowTime": 1573396380,
                "dewPoint": 12.47,
                "humidity": 0.09,
                "pressure": 1016.6,
                "windSpeed": 5.17,
                "windGust": 7.42,
                "windGustTime": 1573308840,
                "windBearing": 23,
                "cloudCover": 0.01,
                "uvIndex": 5,
                "uvIndexTime": 1573328340,
                "visibility": 10,
                "ozone": 261.5,
                "temperatureMin": 66.69,
                "temperatureMinTime": 1573310460,
                "temperatureMax": 87.88,
                "temperatureMaxTime": 1573334520,
                "apparentTemperatureMin": 67.18,
                "apparentTemperatureMinTime": 1573310460,
                "apparentTemperatureMax": 87.38,
                "apparentTemperatureMaxTime": 1573334520
        },
        {
            "time": 1573372800,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1573395720,
                "sunsetTime": 1573433640,
                "moonPhase": 0.46,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipIntensityMaxTime": 1573432020,
                "precipProbability": 0,
                "temperatureHigh": 81.08,
                "temperatureHighTime": 1573420980,
                "temperatureLow": 59.48,
                "temperatureLowTime": 1573481340,
                "apparentTemperatureHigh": 80.58,
                "apparentTemperatureHighTime": 1573420980,
                "apparentTemperatureLow": 59.97,
                "apparentTemperatureLowTime": 1573481340,
                "dewPoint": 18.3,
                "humidity": 0.14,
                "pressure": 1015.1,
                "windSpeed": 4.31,
                "windGust": 5.9,
                "windGustTime": 1573423320,
                "windBearing": 47,
                "cloudCover": 0.02,
                "uvIndex": 5,
                "uvIndexTime": 1573414740,
                "visibility": 10,
                "ozone": 249.9,
                "temperatureMin": 62.88,
                "temperatureMinTime": 1573459200,
                "temperatureMax": 81.08,
                "temperatureMaxTime": 1573420980,
                "apparentTemperatureMin": 63.37,
                "apparentTemperatureMinTime": 1573459200,
                "apparentTemperatureMax": 80.58,
                "apparentTemperatureMaxTime": 1573420980
        },
        {
            "time": 1573459200,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1573482180,
                "sunsetTime": 1573519980,
                "moonPhase": 0.49,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipIntensityMaxTime": 1573527240,
                "precipProbability": 0,
                "temperatureHigh": 84.78,
                "temperatureHighTime": 1573506900,
                "temperatureLow": 63.24,
                "temperatureLowTime": 1573568100,
                "apparentTemperatureHigh": 84.28,
                "apparentTemperatureHighTime": 1573506900,
                "apparentTemperatureLow": 63.73,
                "apparentTemperatureLowTime": 1573568100,
                "dewPoint": 24.72,
                "humidity": 0.19,
                "pressure": 1015.9,
                "windSpeed": 3.33,
                "windGust": 5.5,
                "windGustTime": 1573527780,
                "windBearing": 12,
                "cloudCover": 0,
                "uvIndex": 5,
                "uvIndexTime": 1573501080,
                "visibility": 10,
                "ozone": 250.4,
                "temperatureMin": 59.48,
                "temperatureMinTime": 1573481340,
                "temperatureMax": 84.78,
                "temperatureMaxTime": 1573506900,
                "apparentTemperatureMin": 59.97,
                "apparentTemperatureMinTime": 1573481340,
                "apparentTemperatureMax": 84.28,
                "apparentTemperatureMaxTime": 1573506900
        },
        {
            "time": 1573545600,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1573568640,
                "sunsetTime": 1573606320,
                "moonPhase": 0.52,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipIntensityMaxTime": 1573593060,
                "precipProbability": 0,
                "temperatureHigh": 85.52,
                "temperatureHighTime": 1573592160,
                "temperatureLow": 62.27,
                "temperatureLowTime": 1573654380,
                "apparentTemperatureHigh": 85.02,
                "apparentTemperatureHighTime": 1573592160,
                "apparentTemperatureLow": 62.76,
                "apparentTemperatureLowTime": 1573654380,
                "dewPoint": 22.17,
                "humidity": 0.16,
                "pressure": 1017.5,
                "windSpeed": 3.58,
                "windGust": 6.48,
                "windGustTime": 1573602780,
                "windBearing": 30,
                "cloudCover": 0.15,
                "uvIndex": 5,
                "uvIndexTime": 1573587240,
                "visibility": 10,
                "ozone": 251.5,
                "temperatureMin": 63.24,
                "temperatureMinTime": 1573568100,
                "temperatureMax": 85.52,
                "temperatureMaxTime": 1573592160,
                "apparentTemperatureMin": 63.73,
                "apparentTemperatureMinTime": 1573568100,
                "apparentTemperatureMax": 85.02,
                "apparentTemperatureMaxTime": 1573592160
        },
        {
            "time": 1573632000,
                "summary": "Overcast throughout the day.",
                "icon": "cloudy",
                "sunriseTime": 1573655100,
                "sunsetTime": 1573692720,
                "moonPhase": 0.55,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipIntensityMaxTime": 1573675800,
                "precipProbability": 0,
                "temperatureHigh": 82.08,
                "temperatureHighTime": 1573678800,
                "temperatureLow": 55.61,
                "temperatureLowTime": 1573740540,
                "apparentTemperatureHigh": 81.58,
                "apparentTemperatureHighTime": 1573678800,
                "apparentTemperatureLow": 56.1,
                "apparentTemperatureLowTime": 1573740540,
                "dewPoint": 28.58,
                "humidity": 0.25,
                "pressure": 1015.1,
                "windSpeed": 3.35,
                "windGust": 5.24,
                "windGustTime": 1573712820,
                "windBearing": 131,
                "cloudCover": 0.95,
                "uvIndex": 3,
                "uvIndexTime": 1573673940,
                "visibility": 10,
                "ozone": 258.4,
                "temperatureMin": 58.46,
                "temperatureMinTime": 1573718400,
                "temperatureMax": 82.08,
                "temperatureMaxTime": 1573678800,
                "apparentTemperatureMin": 58.95,
                "apparentTemperatureMinTime": 1573718400,
                "apparentTemperatureMax": 81.58,
                "apparentTemperatureMaxTime": 1573678800
        },
        {
            "time": 1573718400,
                "summary": "Overcast throughout the day.",
                "icon": "cloudy",
                "sunriseTime": 1573741560,
                "sunsetTime": 1573779060,
                "moonPhase": 0.59,
                "precipIntensity": 0.0001,
                "precipIntensityMax": 0.0003,
                "precipIntensityMaxTime": 1573796100,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperatureHigh": 78.69,
                "temperatureHighTime": 1573766880,
                "temperatureLow": 55.87,
                "temperatureLowTime": 1573827060,
                "apparentTemperatureHigh": 78.19,
                "apparentTemperatureHighTime": 1573766880,
                "apparentTemperatureLow": 56.36,
                "apparentTemperatureLowTime": 1573827060,
                "dewPoint": 39.36,
                "humidity": 0.41,
                "pressure": 1015.7,
                "windSpeed": 3.52,
                "windGust": 5.78,
                "windGustTime": 1573775460,
                "windBearing": 109,
                "cloudCover": 0.85,
                "uvIndex": 3,
                "uvIndexTime": 1573760160,
                "visibility": 10,
                "ozone": 267.9,
                "temperatureMin": 55.61,
                "temperatureMinTime": 1573740540,
                "temperatureMax": 78.69,
                "temperatureMaxTime": 1573766880,
                "apparentTemperatureMin": 56.1,
                "apparentTemperatureMinTime": 1573740540,
                "apparentTemperatureMax": 78.19,
                "apparentTemperatureMaxTime": 1573766880
        }
          ]
    },
        "flags": {
        "sources": [
        "nwspa",
                "cmc",
                "gfs",
                "hrrr",
                "icon",
                "isd",
                "madis",
                "nam",
                "sref",
                "darksky",
                "nearest-precip"
          ],
        "nearest-station": 2.199,
                "units": "us"
    },
        "offset": -8
    };

    public static STATE_SEAL_RESPONSE =
    {
        "kind": "customsearch#search",
            "context": {
        "title": "GoogleImages"
    },
        "searchInformation": {
        "searchTime": 0.518243,
                "formattedSearchTime": "0.52",
                "totalResults": "5200000",
                "formattedTotalResults": "5,200,000"
    },
        "items": [
        {
            "kind": "customsearch#result",
                "title": "California State Legislature, 2017–18 session - Wikipedia",
                "htmlTitle": "<b>California State</b> Legislature, 2017–18 session - Wikipedia",
                "link": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Seal_of_California.svg",
                "displayLink": "feedproxy.google.com",
                "snippet": "California State Legislature, 2017–18 session - Wikipedia",
                "htmlSnippet": "<b>California State</b> Legislature, 2017–18 session - Wikipedia",
                "mime": "image/svg+xml",
                "image": {
            "contextLink": "http://feedproxy.google.com/~r/wikipedia/QUnQ/~3/oOL3oZaiB-8/California_State_Legislature,_2017%E2%80%9318_session",
                    "height": 399,
                    "width": 400,
                    "byteSize": 389125,
                    "thumbnailLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVNsYMpgDZom61Zwv9_qHMMVxQ2E8aD6oEgFqorhjv0OXOrzE6fPzkpdw&s",
                    "thumbnailHeight": 124,
                    "thumbnailWidth": 124
        }
        }
      ],
    }

    public static AUTOCOMPLETE_RESPONSE = {
        "predictions": [
        {
            "description": "San Jose, CA, USA",
                "id": "c00d0e6ed23a5a6b418841457b33c47430a93a4c",
                "matched_substrings": [
            {
                "length": 5,
                    "offset": 0
            }
      ],
            "place_id": "ChIJ9T_5iuTKj4ARe3GfygqMnbk",
                "reference": "ChIJ9T_5iuTKj4ARe3GfygqMnbk",
                "structured_formatting": {
            "main_text": "San Jose",
                    "main_text_matched_substrings": [
            {
                "length": 5,
                    "offset": 0
            }
      ],
            "secondary_text": "CA, USA"
        },
            "terms": [
            {
                "offset": 0,
                    "value": "San Jose"
            },
            {
                "offset": 10,
                    "value": "CA"
            },
            {
                "offset": 14,
                    "value": "USA"
            }
      ],
            "types": [
            "locality",
                    "political",
                    "geocode"
      ],
        },
        {
            "description": "San Juan Capistrano, CA, USA",
                "id": "3d3961dc0b962a9aee330c19042d1c38ec143643",
                "matched_substrings": [
            {
                "length": 5,
                    "offset": 0
            }
      ],
            "place_id": "ChIJ9wxgAUTt3IARk42-Je8q6BY",
                "reference": "ChIJ9wxgAUTt3IARk42-Je8q6BY",
                "structured_formatting": {
            "main_text": "San Juan Capistrano",
                    "main_text_matched_substrings": [
            {
                "length": 5,
                    "offset": 0
            }
      ],
            "secondary_text": "CA, USA"
        },
            "terms": [
            {
                "offset": 0,
                    "value": "San Juan Capistrano"
            },
            {
                "offset": 21,
                    "value": "CA"
            },
            {
                "offset": 25,
                    "value": "USA"
            }
      ],
            "types": [
            "locality",
                    "political",
                    "geocode"
      ],
        },
        {
            "description": "San Jacinto, CA, USA",
                "id": "e572981470fbfad30d45fef7d7cb811d4f3bcc35",
                "matched_substrings": [
            {
                "length": 5,
                    "offset": 0
            }
      ],
            "place_id": "ChIJF1mAzHhj24AR5EG1Idxv1JY",
                "reference": "ChIJF1mAzHhj24AR5EG1Idxv1JY",
                "structured_formatting": {
            "main_text": "San Jacinto",
                    "main_text_matched_substrings": [
            {
                "length": 5,
                    "offset": 0
            }
      ],
            "secondary_text": "CA, USA"
        },
            "terms": [
            {
                "offset": 0,
                    "value": "San Jacinto"
            },
            {
                "offset": 13,
                    "value": "CA"
            },
            {
                "offset": 17,
                    "value": "USA"
            }
      ],
            "types": [
            "locality",
                    "political",
                    "geocode"
      ],
        },
        {
            "description": "San Juan Bautista, CA, USA",
                "id": "b0bdf2be4822fc67d904fda4c0b9a573cac2aeb1",
                "matched_substrings": [
            {
                "length": 5,
                    "offset": 0
            }
      ],
            "place_id": "ChIJ6VEnutL4kYARZLv1nc3fb2M",
                "reference": "ChIJ6VEnutL4kYARZLv1nc3fb2M",
                "structured_formatting": {
            "main_text": "San Juan Bautista",
                    "main_text_matched_substrings": [
            {
                "length": 5,
                    "offset": 0
            }
      ],
            "secondary_text": "CA, USA"
        },
            "terms": [
            {
                "offset": 0,
                    "value": "San Juan Bautista"
            },
            {
                "offset": 19,
                    "value": "CA"
            },
            {
                "offset": 23,
                    "value": "USA"
            }
      ],
            "types": [
            "locality",
                    "political",
                    "geocode"
      ],
        },
        {
            "description": "San Joaquin, CA, USA",
                "id": "5e7ae46e82de5f6b8b23d4b8faa48a23e384e4dd",
                "matched_substrings": [
            {
                "length": 5,
                    "offset": 0
            }
      ],
            "place_id": "ChIJJ6kWMl-Ak4AR9fnmX0dK9uI",
                "reference": "ChIJJ6kWMl-Ak4AR9fnmX0dK9uI",
                "structured_formatting": {
            "main_text": "San Joaquin",
                    "main_text_matched_substrings": [
            {
                "length": 5,
                    "offset": 0
            }
      ],
            "secondary_text": "CA, USA"
        },
            "terms": [
            {
                "offset": 0,
                    "value": "San Joaquin"
            },
            {
                "offset": 13,
                    "value": "CA"
            },
            {
                "offset": 17,
                    "value": "USA"
            }
      ],
            "types": [
            "locality",
                    "political",
                    "geocode"
      ],
        }
      ],
        "status": "OK"
    }
*/
}
